version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3 
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - cinnamon
  backend:
    image: lightbend-docker-registry.bintray.io/cinnamon/cinnamon-vizceral:0.1
    ports:
      - "8999:8999"
    networks: 
      - cinnamon
    depends_on:
      - elasticsearch
  web:
    image: lightbend-docker-registry.bintray.io/cinnamon/cinnamon-vizceral-frontend:0.1
    ports:
      - "8080:8080"
    networks:
      - cinnamon
    depends_on:
      - backend

networks:
  cinnamon:
